EXP_FOR_MESSAGE = 3
EXP_FOR_VOICE_MINUTE = 1


SUPPORT_ROLE_ID = 0
MODERATOR_ROLE_ID = 0
DEVELOPER_ROLE_ID = 0


GENERAL_CHANNEL_ID = 0
OFFTOP_CHANNEL_ID = 0


TICKET_CHANNEL_ID = 0
TICKET_MESSAGE_ID = 0
TICKET_REPORT_CHANNEL_ID = 0


SHOP_CHANNEL_ID = 0
SHOP_MESSAGE_ID = 0


CUSTOM_VOICE_CREATION_CHANNEL_ID = 0
CUSTOM_VOICE_CATEGORY_ID = 0
CUSTOM_VOICE_DELETION_TIME = 30


COMMAND_INTERACTIONS_WEBHOOK_URL = ""
MESSAGES_WEBHOOK_URL = ""
TICKETS_WEBHOOK_URL = ""
GUILD_WEBHOOK_URL = ""
MEMBERS_WEBHOOK_URL = ""
ELSE_WEBHOOK_URL = ""